### ISSUE TITLE
Can'd adjust input size

### ISSUE THREAD

**Issue by haxx0rman** [lukalabs/cakechat#31]
Trying to increase input size to anything more than 3 results in an error saying I need to download a new model

**Comment by nicolas-ivanov** [comment]
@haxx0rman kindly add  to your question the output of the command you launched, otherwise it's really hard to analyse the error. Do you mean `INPUT_CONTEXT_SIZE` by "context size"?

**Comment by haxx0rman** [comment]
Yes, I am referring to `INPUT_CONTEXT_SIZE`. 
When I take my functioning model  and I simply change `INPUT_CONTEXT_SIZE` from default 3 to 5 I receive this error

`Traceback (most recent call last):
  File "kik/kik_client.py", line 27, in <module>
    from cakechat.api.response import get_response
  File "/home/micky/Dev/Kik Client/Python/test/cakechat/api/response.py", line 16, in <module>
    _cakechat_model = get_trained_model(fetch_from_s3=False)
  File "/home/micky/.local/lib/python3.5/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/home/micky/Dev/Kik Client/Python/test/cakechat/dialog_model/factory.py", line 55, in get_trained_model
    raise FileNotFoundException('Can\'t get the pre-trained model. Run tools/download_model.py first '
cakechat.utils.files_utils.FileNotFoundException: Can't get the pre-trained model. Run tools/download_model.py first to get all required files or train it by yourself.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
^CTraceback (most recent call last):
  File "kik/kik_client.py", line 27, in <module>
    from cakechat.api.response import get_response
  File "/home/micky/Dev/Kik Client/Python/test/cakechat/api/response.py", line 16, in <module>
    _cakechat_model = get_trained_model(fetch_from_s3=False)
  File "/home/micky/.local/lib/python3.5/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/home/micky/Dev/Kik Client/Python/test/cakechat/dialog_model/factory.py", line 53, in get_trained_model
    is_reverse_model=reverse)
  File "/home/micky/Dev/Kik Client/Python/test/cakechat/dialog_model/model.py", line 712, in get_nn_model
    is_reverse_model=is_reverse_model)
  File "/home/micky/Dev/Kik Client/Python/test/cakechat/dialog_model/model.py", line 86, in __init__
    self._build_model_computational_graph()
  File "/home/micky/Dev/Kik Client/Python/test/cakechat/dialog_model/model.py", line 134, in _build_model_computational_graph
    self._add_word_embeddings()
  File "/home/micky/Dev/Kik Client/Python/test/cakechat/dialog_model/model.py", line 186, in _add_word_embeddings
    name='emb_y')
  File "/home/micky/.local/lib/python3.5/site-packages/lasagne/layers/embedding.py", line 63, in __init__
    self.W = self.add_param(W, (input_size, output_size), name="W")
  File "/home/micky/.local/lib/python3.5/site-packages/lasagne/layers/base.py", line 234, in add_param
    param = utils.create_param(spec, shape, name)
  File "/home/micky/.local/lib/python3.5/site-packages/lasagne/utils.py", line 376, in create_param
    spec = spec(shape)
  File "/home/micky/.local/lib/python3.5/site-packages/lasagne/init.py", line 31, in __call__
    return self.sample(shape)
  File "/home/micky/.local/lib/python3.5/site-packages/lasagne/init.py", line 66, in sample
    return floatX(get_rng().normal(self.mean, self.std, size=shape))`

**Comment by nicolas-ivanov** [comment]
@haxx0rman `INPUT_CONTEXT_SIZE` is a parameter that specifies a trained dialog model (along with other parameters from the config file). If you want to apply your dialog model to larger input contexts, you should generally retrain it on a proper data – see `tools/train.py`. 

We trained our model on contexts of lengths up to 3 phrases. This model might also work on larger contexts if you you hack around its name construction process:

* change `INPUT_CONTEXT_SIZE` in the `cakechat/config.py` to the desired value to predict answers for larger contexts
* hardcode `input_cont_size=3` on [this line](https://github.com/lukalabs/cakechat/blob/master/cakechat/dialog_model/model.py#L111) to keep using our trained model.

However, no guarantees that the results will be good :)

**Comment by haxx0rman** [comment]
I've been using your model and training on top of it. Is it more advisable to just start from scratch?
