### ISSUE TITLE
AttributeError: 'module' object has no attribute '_get_ndarray_c_version'

### ISSUE THREAD

**Issue by 4R7I5T** [lukalabs/cakechat#56]
Outputs this right here... Not quite sure how to fix...

Tried deleting the stuff in w2v_models to no avail - help! 

```
[17.05.2019 14:44:06.637][INFO][11844][cakechat.utils.files_utils][87] Loading /root/cakechat/data/tensorboard/steps
[17.05.2019 14:44:06.637][INFO][11844][cakechat.tools/train.py][102] THEANO_FLAGS: floatX=float32,device=cpu
[17.05.2019 14:44:06.639][INFO][11844][cakechat.tools/train.py][42] Getting train iterator for w2v...
[17.05.2019 14:44:06.639][INFO][11844][cakechat.tools/train.py][48] Getting text-filtered train iterator...
[17.05.2019 14:44:06.639][INFO][11844][cakechat.tools/train.py][51] Getting tokenized train iterator...
[17.05.2019 14:44:06.640][INFO][11844][cakechat.utils.w2v.model][64] Getting w2v model
[17.05.2019 14:44:06.789][INFO][11844][cakechat.utils.s3.bucket][19] Getting file w2v_models/train_LUCI_window10_voc891_vec128_sgTrue.bin from AWS S3 and saving it as /root/cakechat/data/w2v_models/train_LUCI_window10_voc891_vec128_sgTrue.bin
[17.05.2019 14:44:07.206][WARNING][11844][cakechat.utils.s3.resolver.S3FileResolver][42] File can not be downloaded from AWS S3 because: An error occurred (404) when calling the HeadObject operation: Not Found
[17.05.2019 14:44:07.206][INFO][11844][cakechat.utils.w2v.model][18] Word2Vec model will be trained now. It can take long, so relax and have fun.
[17.05.2019 14:44:07.206][INFO][11844][cakechat.utils.w2v.model][21] Parameters for training: window10_voc891_vec128_sgTrue
[17.05.2019 14:44:07.255][INFO][11844][cakechat.utils.w2v.model][44] Saving model to /root/cakechat/data/w2v_models/train_LUCI_window10_voc891_vec128_sgTrue.bin
[17.05.2019 14:44:07.263][INFO][11844][cakechat.utils.w2v.model][47] Model has been saved
[17.05.2019 14:44:07.263][INFO][11844][cakechat.utils.w2v.model][80] Successfully got w2v model

[17.05.2019 14:44:07.263][INFO][11844][cakechat.dialog_model.model_utils][202] Preparing embedding matrix based on w2v_model and index_to_token dict
[17.05.2019 14:44:07.263][WARNING][11844][cakechat.dialog_model.model_utils][192] Can't find token [_unk_] in w2v dict
Traceback (most recent call last):
  File "tools/train.py", line 107, in <module>
    train(init_path=args.init_weights, is_reverse_model=args.reverse)
  File "tools/train.py", line 79, in train
    resolver_factory=nn_model_resolver_factory, is_reverse_model=is_reverse_model)
  File "/root/cakechat/cakechat/dialog_model/model.py", line 714, in get_nn_model
    is_reverse_model=is_reverse_model)
  File "/root/cakechat/cakechat/dialog_model/model.py", line 88, in __init__
    self._compile_theano_functions_for_prediction()
  File "/root/cakechat/cakechat/dialog_model/model.py", line 144, in _compile_theano_functions_for_prediction
    self.predict_prob = self._get_predict_fn(logarithm_output_probs=False)
  File "/root/cakechat/cakechat/dialog_model/model.py", line 464, in _get_predict_fn
    output_probs = self._get_nn_output()
  File "/root/cakechat/cakechat/dialog_model/model.py", line 443, in _get_nn_output
    output_probs = get_output(self._net['dist'], deterministic=True)
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/helper.py", line 197, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/recurrent.py", line 1489, in get_output_for
    strict=True)[0]
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan.py", line 1048, in scan
    local_op = scan_op.Scan(inner_inputs, new_outs, info)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 216, in __init__
    [])
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1300, in cmodule_key_variables
    c_compiler)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1350, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: 'module' object has no attribute '_get_ndarray_c_version'
```

**Comment by nicolas-ivanov** [comment]
@4R7I5T could you please post the output of `git diff` with your changes of the code?

**Comment by nicolas-ivanov** [comment]
Also I see that your vocabulary only has 891 tokens:

> Saving model to /root/cakechat/data/w2v_models/train_LUCI_window10_voc891_vec128_sgTrue.bin
[17.05.2019 14:44:07.263][INFO][11844][cakechat.utils.w2v.model][47] Model has been saved

 and no `_unk_` token:

> Can't find token [_unk_] in w2v dict

Vocabulary with 891 tokens is too small for real-life use case, don't expect getting good results with.

**Comment by 4R7I5T** [comment]
> Also I see that your vocabulary only has 891 tokens:
> 
> > Saving model to /root/cakechat/data/w2v_models/train_LUCI_window10_voc891_vec128_sgTrue.bin
> > [17.05.2019 14:44:07.263][INFO][11844][cakechat.utils.w2v.model][47] Model has been saved
> 
> and no `_unk_` token:
> 
> > Can't find token [_unk_] in w2v dict
> 
> Vocabulary with 891 tokens is too small for real-life use case, don't expect getting good results with.

So probably the data set is just too small?

I'm a bit new to machine learning so any advice is helpful

**Comment by nicolas-ivanov** [comment]
Apparently it is. How many training samples do you have there?

**Comment by 4R7I5T** [comment]
> Apparently it is. How many training samples do you have there?

Really not much, exactly how big should this be? and also the _unk_ token - is this automatically generated? 

Thanks

**Comment by nicolas-ivanov** [comment]
I'd say 50Mb of raw data at least – if your want to train from scratch. 

`_unk_` token is generated automatically, if the number of unique tokens in your train dataset is bigger then the value of  `VOCABULARY_MAX_SIZE` param – in this case you'll automatically get out-of-vocabulary tokens. Otherwise you may add `_unk_` token to your train dataset manually.
