### ISSUE TITLE
Syntax Error:Invalid Syntax

### ISSUE THREAD

**Issue by RudyAramayo** [lukalabs/cakechat#59]
Compiled on MacOSX 10.14.5

executed "pip install -r requirements.txt -r requirements-local.txt"
then "open cakechat/cakechat/api/config.py" to remove emoji character because it was complaining about non-ascii character encoding
then "python cakechat_server.py -b 127.0.0.1:8080" from the bin directory

Should I update python? 2.7.15

Using TensorFlow backend.
[2019-06-01 11:08:31 -0700] [52444] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/rob/Desktop/cakechat_v2./bin/cakechat_server.py", line 11, in <module>
    from cakechat.api.v1.server import app
  File "/Users/rob/Desktop/cakechat_v2./cakechat/api/v1/server.py", line 3, in <module>
    from cakechat.api.response import get_response
  File "/Users/rob/Desktop/cakechat_v2./cakechat/api/response.py", line 6, in <module>
    from cakechat.dialog_model.factory import get_trained_model, get_reverse_model
  File "/Users/rob/Desktop/cakechat_v2./cakechat/dialog_model/factory.py", line 8, in <module>
    from cakechat.dialog_model.inference_model import InferenceCakeChatModel
  File "/Users/rob/Desktop/cakechat_v2./cakechat/dialog_model/inference_model.py", line 1, in <module>
    from cakechat.dialog_model.keras_model import KerasTFModelIsolator
  File "/Users/rob/Desktop/cakechat_v2./cakechat/dialog_model/keras_model.py", line 114
    class AbstractKerasModel(AbstractModel, metaclass=abc.ABCMeta):

SyntaxError: invalid syntax
[2019-06-01 11:08:31 -0700] [52444] [INFO] Worker exiting (pid: 52444)
[2019-06-01 11:08:31 -0700] [52441] [INFO] Shutting down: Master
[2019-06-01 11:08:31 -0700] [52441] [INFO] Reason: Worker failed to boot.

**Comment by nicolas-ivanov** [comment]
@RudyAramayo please notice, that since the recent major release only python 3 is supported. You need python 3.5.2 or above. We'll add this info to our Readme file for better clarity.

**Comment by RudyAramayo** [comment]
Thankyou!

**Comment by nicolas-ivanov** [comment]
Sure thing
https://github.com/lukalabs/cakechat/pull/60
