### ISSUE TITLE
cannot get trained model

### ISSUE THREAD

**Issue by chukrobertson** [lukalabs/cakechat#65]
please close this.

**Comment by chukrobertson** [comment]
tried running as <code>python3 tools/fetch.py</code> and got a new error.

<code>chuk@FoxxBoxx:~/Projects/cakechat$ python3 tools/fetch.py
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0718 23:03:48.194006 140243881621312 deprecation_wrapper.py:119] From /home/chuk/Projects/cakechat/cakechat/utils/env.py:47: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0718 23:03:48.194361 140243881621312 deprecation_wrapper.py:119] From /home/chuk/Projects/cakechat/cakechat/utils/env.py:54: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-07-18 23:03:48.240882: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2394500000 Hz
2019-07-18 23:03:48.241757: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x245ac10 executing computations on platform Host. Devices:
2019-07-18 23:03:48.241818: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "tools/fetch.py", line 15, in <module>
    from cakechat.dialog_model.factory import get_trained_model
  File "/home/chuk/Projects/cakechat/cakechat/dialog_model/factory.py", line 3, in <module>
    from cachetools import cached
ModuleNotFoundError: No module named 'cachetools'
</code>

**Comment by nicolas-ivanov** [comment]
Ok!
