### ISSUE TITLE
Gives import error on running fetch.py

### ISSUE THREAD

**Issue by rojagtap** [lukalabs/cakechat#74]
Installed the requirements on fresh conda environment.
Python: 3.5.2
But executing fetch.py gives:

```
Using TensorFlow backend.
2019-10-29 22:33:53.308493: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "tools/fetch.py", line 15, in <module>
    from cakechat.dialog_model.factory import get_trained_model
  File "E:\cakechat\cakechat\dialog_model\factory.py", line 8, in <module>
    from cakechat.dialog_model.inference_model import InferenceCakeChatModel
  File "E:\cakechat\cakechat\dialog_model\inference_model.py", line 1, in <module>
    from cakechat.dialog_model.keras_model import KerasTFModelIsolator
  File "E:\cakechat\cakechat\dialog_model\keras_model.py", line 11, in <module>
    from cakechat.dialog_model.abstract_model import AbstractModel
  File "E:\cakechat\cakechat\dialog_model\abstract_model.py", line 6, in <module>
    from cakechat.dialog_model.quality.metrics.utils import MetricsSerializer
  File "E:\cakechat\cakechat\dialog_model\quality\__init__.py", line 2, in <module>
    from cakechat.dialog_model.quality.metrics.lexical_simlarity import calculate_lexical_similarity, get_tfidf_vectorizer
  File "E:\cakechat\cakechat\dialog_model\quality\metrics\lexical_simlarity.py", line 3, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
  File "C:\Users\Rohan\.conda\envs\cakechat\lib\site-packages\sklearn\__init__.py", line 64, in <module>
    from .base import clone
  File "C:\Users\Rohan\.conda\envs\cakechat\lib\site-packages\sklearn\base.py", line 13, in <module>
    from .utils.fixes import signature
  File "C:\Users\Rohan\.conda\envs\cakechat\lib\site-packages\sklearn\utils\__init__.py", line 16, in <module>
    from .fixes import _Sequence as Sequence
  File "C:\Users\Rohan\.conda\envs\cakechat\lib\site-packages\sklearn\utils\fixes.py", line 92, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "C:\Users\Rohan\.conda\envs\cakechat\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .isolve import *
  File "C:\Users\Rohan\.conda\envs\cakechat\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "C:\Users\Rohan\.conda\envs\cakechat\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 10, in <module>
    from . import _iterative
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by nicolas-ivanov** [comment]
@rojagtap Sorry for the delay with the answer! Let's check the version of scipy: execute `conda list` from your environment and send the output.
